### ISSUE TITLE
Wemo.timeout is not defined

### ISSUE THREAD

**Issue by Nibbler999** [hecomi/node-wemo#6]
https://github.com/hecomi/node-wemo/blob/master/wemo.js#L91

```
req.on('socket', function(socket) {
    socket.setTimeout(WeMo.timeout);
    socket.on('timeout', function() {
        req.abort();
        callback('Timeout access to WeMo@' + options.host + ':' + options.port, null);
    });
});
```

**Comment by hecomi** [comment]
Sorry for my late reply. I fixed this bug at https://github.com/hecomi/node-wemo/commit/f82b4900ec7404d09d01bd4babb9a53d05c4e532.
Thank you for your report!
